spring.application.name=license-service
server.port=8005

# Vault Configuration
vault.uri=${VAULT_ADDR:http://openbao:8200}
vault.token=${VAULT_TOKEN:root}

# Actuator
management.endpoints.web.exposure.include=health,info
