apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-mcp-service
  namespace: k8sdemo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ai-mcp-service
  template:
    metadata:
      labels:
        app: ai-mcp-service
        env: production
        managed-by: argocd
      annotations:
        deployed-at: "2026-05-14 01:27:58"
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
      - name: ai-mcp
        image: ghcr.io/darkschneider1024/ai-mcp-service:7c535f92cf42adef50b27993629fed4d95731133
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: GEMINI_API_KEY
        - name: DELTA_PATH
          value: "/app/wafer_delta_table"
        volumeMounts:
        - name: chroma-storage
          mountPath: /app/chroma_db
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: chroma-storage
        persistentVolumeClaim:
          claimName: chroma-data-pvc
