apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8sdemo
  labels:
    app: frontend
    app.kubernetes.io/part-of: k8sdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
        - name: frontend
          image: ap-tokyo-1.ocir.io/nrf3s0wa8lv5/wafer-bi-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 10
