apiVersion: v1
kind: ConfigMap
metadata:
  name: wafer-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "wafer-bi.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.waferConfig.viteApiUrl | quote }}
