apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8sdemo
  labels:
    app: frontend
    app.kubernetes.io/part-of: k8sdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        env: production
        managed-by: argocd
    spec:
      imagePullSecrets:
        - name: ocirsecret
      containers:
        - name: frontend
          image: ghcr.io/darkschneider1024/wafer-bi-frontend:c385f2d11933c0993035f2d80d28766c5d13458c
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
