apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8sdemo-ingress
  namespace: k8sdemo
  labels:
    app.kubernetes.io/part-of: k8sdemo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wafer.carrot-atelier.online
      secretName: wafer-bi-tls
  rules:
    - host: wafer.carrot-atelier.online
      http:
        paths:
          # API Gateway (Auth & Wafer BI Routing)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 8080
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 8080
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 8080
          # Wafer BI Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wafer-frontend-svc
                port:
                  number: 80
          # Jaeger UI (Observability)
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger-service
                port:
                  number: 16686
