apiVersion: v1
kind: ConfigMap
metadata:
  name: wafer-config
  namespace: k8sdemo
data:
  # This value is safe to be public but can be overridden
  VITE_API_URL: "https://wafer.carrot-atelier.online/api"
