apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app-config.yaml
  - configmap.yaml
  - cluster-issuer.yaml
  - ingress.yaml
  - network-policy.yaml
  - service-proxy.yaml
  - wafer-bi-deployment.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml
  - user-service/deployment.yaml
  - user-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - databases/postgres-deployment.yaml
  - databases/postgres-pvc.yaml
  - databases/postgres-service.yaml
  - observability/jaeger.yaml
  - observability/otel-collector.yaml
